baseURL = "https://fotographicparets.com/"
languageCode = "es"
defaultContentLanguage = "es"
title = "FOTOgraphic Parets 2019"
theme = "fotographic-theme"
sectionPagesMenu = "main"
[menu]
    [[menu.main]]
        name = "Inicio"
        identifier = "Inicio"
        url = "/"
        weight = 10
    [[menu.main]]
        name = "Programa"
        identifier = "programa"
        url = "/programa/"
        weight = 20
    [[menu.main]]
        name = "Ponentes"
        identifier = "ponentes"
        url = "/ponentes/"
        weight = 30
    [[menu.main]]
        name = "Exposición"
        identifier = "exposicion"
        url = "/exposicion/"
        weight = 40
    [[menu.main]]
        name = "Guía"
        identifier = "guia-visitante"
        url = "/guia-visitante/"
        weight = 50
    [[menu.main]]
        name = "Agradecimientos"
        identifier = "agradecimientos"
        url = "/agradecimientos/"
        weight = 60   
    [[menu.main]]
        name = "AFParets"
        identifier = "quines-somos"
        url = "/agradecimientos/"
        weight = 70  
    [[menu.main]]
        name = "Opiniones"
        identifier = "profesional-opina"
        url = "/agradecimientos/"
        weight = 80  
[params]
  author = "Alex Bibiano"
  description = "FOTOgraphic Parets 2019, 7ª edición del evento fotográfico pensado para todos los amantes de la fotografía con ponencias, talleres y exposiciones gratuitas."