baseURL = "https://fotographicparets.com/"
languageCode = "es"
defaultContentLanguage = "es"
title = "FOTOgraphic Parets 2022"

[params]
  author = "Alex Bibiano"
  description = "FOTOgraphic Parets 2022, 9ª edición del evento fotográfico pensado para todos los amantes de la fotografía con ponencias, talleres y exposiciones gratuitas."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/scss"
    target = "assets/scss/bootstrap"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"        
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"    

sectionPagesMenu = "main"
