baseURL = "https://fotographicparets.com/"
locale = "ca"
defaultContentLanguage = "ca"
title = "FOTOgraphic Parets 2026"

[params]
  author = "Alex Bibiano"
  description = "FOTOgraphic Parets 2026, 13a edició de l'esdeveniment fotogràfic amb bodegons, ponències i tallers a Parets del Vallès."
  theme_color = "#4a4a4a"

  [params.seo]
    default_image = "originales/logo-fotographic-negre.jpg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/scss"
    target = "assets/scss/bootstrap"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"

sectionPagesMenu = "main"
